### PR TITLE
Create DebianInstall.sh

### PR DESCRIPTION
**Pull request by hellresistor**
A Basic Script To Install Configure and Set ONE USER PANIC password.

### CODE REVIEW

**Comment by hellresistor** [comment]
Has Changed repository because @Lqp1 has updated to Debian 11

**Comment by Lqp1** [comment]
I don't understand why you clone the respository in your script; I think we can safely assume that if the script is downloaded, it comes from a `git clone`. I think it's better if you skip `git clone` part and just make your script relative to its directory. Or make this script a github gist maybe?

If you found some differences in recent debian configuration, you can also add specific entries in README.md to document that.

Thanks for your interest!

**Comment by hellresistor** [comment]
Litke this ?
https://gist.github.com/hellresistor/e5a6d9cc3a138ac70603b6fdda7ea588

**Comment by Lqp1** [comment]
Yep, if you want. Don't hesitate to propose an updated README for Debian 10 if you found something interesting :)

**Comment by hellresistor** [comment]
Thank you for tips :) @Lqp1

**Pull request closed without merging**
